export interface StockInfo {
  ticker: string;
  company: string;
  focus: string;
  risk: string;
}

export interface StockCategory {
  name: string;
  color: string;
  description: string;
  stocks: StockInfo[];
}

export const CATEGORIES: StockCategory[] = [
  {
    name: "⚛️ Quantum Computing",
    color: "7030A0",
    description: "High-risk quantum plays — potential 10× returns within 2 years",
    stocks: [
      { ticker: "IONQ",  company: "IonQ Inc",              focus: "Quantum computing hardware & software",        risk: "Very High" },
      { ticker: "RGTI",  company: "Rigetti Computing",      focus: "Quantum computing chips & systems",           risk: "Very High" },
      { ticker: "QBTS",  company: "D-Wave Quantum",         focus: "Quantum annealing systems",                   risk: "Very High" },
      { ticker: "QUBT",  company: "Quantum Computing Inc",  focus: "Quantum software & photonics hardware",       risk: "Very High" },
      { ticker: "ARQQ",  company: "Arqit Quantum",          focus: "Satellite quantum key distribution / crypto", risk: "Very High" },
      { ticker: "LAES",  company: "SEALSQ Corp",            focus: "Post-quantum cryptography chips",             risk: "Very High" },
    ],
  },
  {
    name: "🖥️ Semiconductors & Compute",
    color: "0070C0",
    description: "Core semiconductor & compute names — stability + steady compounders",
    stocks: [
      { ticker: "NVDA",  company: "NVIDIA Corp",            focus: "GPUs, AI compute",                                    risk: "Medium"   },
      { ticker: "AVGO",  company: "Broadcom Inc",           focus: "Semiconductors, networking",                          risk: "Medium"   },
      { ticker: "LRCX",  company: "Lam Research",           focus: "Semiconductor equipment, DRAM",                       risk: "Medium"   },
      { ticker: "AMD",   company: "Advanced Micro Devices", focus: "CPUs, GPUs, AI chips",                                risk: "Medium"   },
      { ticker: "INTC",  company: "Intel Corp",             focus: "CPUs, AI accelerators",                               risk: "Med-High" },
      { ticker: "ARM",   company: "Arm Holdings",           focus: "Chip architecture licensing",                         risk: "Medium"   },
      { ticker: "MRVL",  company: "Marvell Technology",     focus: "Custom AI ASICs, networking silicon",                 risk: "Medium"   },
      { ticker: "KLAC",  company: "KLA Corporation",        focus: "Semiconductor process control equip",                 risk: "Medium"   },
      { ticker: "TSM",   company: "Taiwan Semiconductor",   focus: "Leading global foundry, 2nm+ node",                   risk: "Med-High" },
      { ticker: "ASML",  company: "ASML Holding",           focus: "EUV lithography — monopoly on leading-edge chip production", risk: "Medium" },
      { ticker: "AMAT",  company: "Applied Materials",      focus: "Semiconductor deposition & etch equipment",           risk: "Medium"   },
      { ticker: "MU",    company: "Micron Technology",      focus: "HBM & DRAM memory critical for AI compute",           risk: "Medium"   },
      { ticker: "QCOM",  company: "Qualcomm",               focus: "AI inference chips for edge & mobile",                risk: "Medium"   },
      { ticker: "ON",    company: "ON Semiconductor",       focus: "Power & sensing semiconductors for AI/EVs",           risk: "Med-High" },
    ],
  },
  {
    name: "⚙️ AI Picks & Shovels",
    color: "C55A11",
    description: "Smaller-cap NVDA-adjacent setups — high risk, asymmetric upside",
    stocks: [
      { ticker: "NVTS",  company: "Navitas Semiconductor",  focus: "GaN power chips for AI data centers",                 risk: "High"      },
      { ticker: "AEHR",  company: "AEHR Test Systems",      focus: "Semiconductor burn-in & test equipment",              risk: "High"      },
      { ticker: "CRDO",  company: "Credo Technology",       focus: "High-speed connectivity / SerDes for AI DCs",         risk: "High"      },
      { ticker: "ALGM",  company: "Allegro MicroSystems",   focus: "Power & sensing semiconductors",                      risk: "Med-High"  },
      { ticker: "HIMX",  company: "Himax Technologies",     focus: "Display drivers + AR/AI vision chips",                risk: "High"      },
      { ticker: "MTSI",  company: "MACOM Technology",       focus: "RF, microwave, high-speed analog chips",              risk: "Med-High"  },
      { ticker: "AEVA",  company: "Aeva Technologies",      focus: "Lidar + sensing for autonomous systems",              risk: "Very High" },
      { ticker: "SMCI",  company: "Super Micro Computer",   focus: "AI server systems & rack integration",                risk: "High"      },
      { ticker: "SITM",  company: "SiTime Corp",            focus: "Precision timing semiconductors for AI",              risk: "High"      },
      { ticker: "CEVA",  company: "CEVA Inc",               focus: "AI chip IP licensing, DSP cores",                     risk: "Med-High"  },
      { ticker: "AUR",   company: "Aurora Innovation",      focus: "Autonomous driving software & sensor platform",       risk: "Very High" },
      { ticker: "OUST",  company: "Ouster Inc",             focus: "Digital LiDAR sensors for robotics & AV",             risk: "Very High" },
      { ticker: "RMBS",  company: "Rambus Inc",             focus: "Chip interface IP + HBM memory solutions",            risk: "Med-High"  },
      { ticker: "ONTO",  company: "Onto Innovation",        focus: "Optical metrology & inspection for advanced nodes",   risk: "High"      },
      { ticker: "ACMR",  company: "ACM Research",           focus: "Semiconductor wet cleaning equipment",                risk: "High"      },
      { ticker: "PI",    company: "Impinj Inc",             focus: "RAIN RFID & IoT edge connectivity platform",          risk: "Med-High"  },
      { ticker: "COHU",  company: "Cohu Inc",               focus: "Semiconductor test handlers & contactors",            risk: "High"      },
      { ticker: "MRAM",  company: "Everspin Technologies",  focus: "STT-MRAM chips for industrial, aerospace & storage",  risk: "High"      },
      { ticker: "NVEC",  company: "NVE Corporation",        focus: "Spintronic sensors, couplers & MRAM technology",      risk: "High"      },
    ],
  },
  {
    name: "💡 Photonics & Optics",
    color: "00B0F0",
    description: "Optical networking — key bottleneck in AI data center interconnect",
    stocks: [
      { ticker: "LITE",  company: "Lumentum Holdings",       focus: "Photonics, optical components for AI DCs",           risk: "High"     },
      { ticker: "COHR",  company: "Coherent Corp",           focus: "Optical transceivers & photonic integration",         risk: "High"     },
      { ticker: "AAOI",  company: "Applied Optoelectronics", focus: "Optical transceivers for hyperscale DCs",             risk: "High"     },
      { ticker: "IPGP",  company: "IPG Photonics",           focus: "High-power fiber lasers & amplifiers",                risk: "Med-High" },
      { ticker: "CIEN",  company: "Ciena Corp",              focus: "Optical networking systems for AI DC interconnect",   risk: "Med-High" },
      { ticker: "INFN",  company: "Infinera Corp",           focus: "Optical transport networking equipment",              risk: "High"     },
      { ticker: "VIAV",  company: "Viavi Solutions",         focus: "Fiber optic test, measurement & network tools",       risk: "Med-High" },
      { ticker: "ADTN",  company: "ADTRAN Holdings",         focus: "Optical networking & broadband access equipment",     risk: "High"     },
      { ticker: "CALX",  company: "Calix Networks",          focus: "Cloud & broadband access platforms",                  risk: "Med-High" },
      { ticker: "NOK",   company: "Nokia Corp",              focus: "5G network equipment, IP routing & optical networking", risk: "Medium"   },
    ],
  },
  {
    name: "🏗️ DC Builders & Cooling",
    color: "375623",
    description: "Builders, materials, and cooling companies powering AI data center construction",
    stocks: [
      { ticker: "CAT",   company: "Caterpillar Inc",         focus: "Heavy equipment, construction",                       risk: "Low-Med" },
      { ticker: "FIX",   company: "Comfort Systems USA",     focus: "HVAC, mechanical, electrical for DCs",                risk: "Medium"  },
      { ticker: "POWL",  company: "Powell Industries",       focus: "Electrical infrastructure for DCs",                   risk: "Medium"  },
      { ticker: "VRT",   company: "Vertiv Holdings",         focus: "Cooling systems for AI data centers",                 risk: "Medium"  },
      { ticker: "ETN",   company: "Eaton Corp",              focus: "Power management & distribution for DCs",             risk: "Low-Med" },
      { ticker: "IR",    company: "Ingersoll Rand",          focus: "Industrial cooling & air compression",                risk: "Low-Med" },
      { ticker: "HUBB",  company: "Hubbell Inc",             focus: "Electrical infrastructure & connectors",              risk: "Low-Med" },
      { ticker: "STRL",  company: "Sterling Infrastructure", focus: "Civil construction for data centers & utilities",     risk: "Medium"  },
      { ticker: "AGX",   company: "Argan Inc",               focus: "Power plant EPC construction serving DC buildout",    risk: "Medium"  },
      { ticker: "EMR",   company: "Emerson Electric",        focus: "Industrial automation & HVAC control systems",        risk: "Low-Med" },
      { ticker: "SPXC",  company: "SPX Technologies",        focus: "HVAC, cooling & detection systems",                   risk: "Medium"  },
      { ticker: "J",     company: "Jacobs Solutions",        focus: "Engineering & construction services for DC projects", risk: "Low-Med" },
      { ticker: "DELL",  company: "Dell Technologies",       focus: "AI servers, PowerEdge compute & enterprise storage",  risk: "Medium"  },
    ],
  },
  {
    name: "⚡ Power & Energy",
    color: "ED7D31",
    description: "Power generation, grid maintenance & nuclear energy for the AI buildout",
    stocks: [
      { ticker: "GEV",   company: "GE Vernova",          focus: "Power generation & grid equipment",                       risk: "Medium"    },
      { ticker: "PWR",   company: "Quanta Services",     focus: "Power grid infrastructure & maintenance",                  risk: "Medium"    },
      { ticker: "BE",    company: "Bloom Energy",        focus: "Fuel cell power generation",                              risk: "High"      },
      { ticker: "OKLO",  company: "Oklo Inc",            focus: "Nuclear SMRs + nuclear fuel waste",                        risk: "Very High" },
      { ticker: "CEG",   company: "Constellation Energy",focus: "Largest US nuclear power operator",                        risk: "Medium"    },
      { ticker: "SMR",   company: "NuScale Power",       focus: "Small modular reactor technology",                         risk: "Very High" },
      { ticker: "NNE",   company: "Nano Nuclear Energy", focus: "Portable microreactors & nuclear fuel",                    risk: "Very High" },
      { ticker: "AMPX",  company: "Amprius Technologies",focus: "Ultra-high energy density silicon anode batteries",        risk: "Very High" },
      { ticker: "VST",   company: "Vistra Corp",         focus: "Nuclear + gas power generation, AI data center PPAs",      risk: "Medium"    },
      { ticker: "BWXT",  company: "BWX Technologies",    focus: "Nuclear components & reactor technology for gov/DC",       risk: "Medium"    },
      { ticker: "TLN",   company: "Talen Energy",        focus: "Nuclear power with dedicated data center agreements",       risk: "Med-High"  },
      { ticker: "NEE",   company: "NextEra Energy",      focus: "Largest US renewable energy & utility operator",           risk: "Low-Med"   },
      { ticker: "D",     company: "Dominion Energy",     focus: "Large utility with significant nuclear fleet",             risk: "Low-Med"   },
    ],
  },
  {
    name: "☁️ Neoclouds & AI Software",
    color: "5A2E8C",
    description: "Next-gen cloud infrastructure and AI software platforms",
    stocks: [
      { ticker: "MSFT",  company: "Microsoft Corp",          focus: "Azure cloud, Copilot AI, enterprise software",          risk: "Low-Med"  },
      { ticker: "NOW",   company: "ServiceNow Inc",           focus: "AI-powered enterprise workflow automation platform",      risk: "Medium"   },
      { ticker: "NBIS",  company: "Nebius Group",          focus: "Neocloud + Clickhouse + AV Ride",                       risk: "High"     },
      { ticker: "PLTR",  company: "Palantir Technologies", focus: "AI software, government AI stack",                       risk: "Med-High" },
      { ticker: "RBRK",  company: "Rubrik Inc",            focus: "Cybersecurity, data management",                         risk: "Med-High" },
      { ticker: "NET",   company: "Cloudflare Inc",        focus: "AI edge networking & zero-trust security",               risk: "Med-High" },
      { ticker: "SNOW",  company: "Snowflake Inc",         focus: "AI/ML data platform & data cloud",                       risk: "Med-High" },
      { ticker: "SOUN",  company: "SoundHound AI",         focus: "AI voice & conversational intelligence",                 risk: "High"     },
      { ticker: "BB",    company: "BlackBerry Ltd",        focus: "Cybersecurity software & IoT platform",                  risk: "High"     },
      { ticker: "RDDT",  company: "Reddit Inc",            focus: "Social platform with AI data licensing & ad revenue",    risk: "Med-High" },
      { ticker: "DDOG",  company: "Datadog Inc",           focus: "AI observability, monitoring & security platform",       risk: "Med-High" },
      { ticker: "GTLB",  company: "GitLab Inc",            focus: "AI DevOps platform & code intelligence",                 risk: "Med-High" },
      { ticker: "PATH",  company: "UiPath Inc",            focus: "AI process automation & RPA platform",                   risk: "Med-High" },
      { ticker: "MDB",   company: "MongoDB Inc",           focus: "AI-era document database & cloud data platform",         risk: "Med-High" },
      { ticker: "CRWD",  company: "CrowdStrike Holdings",  focus: "AI-native endpoint & cloud cybersecurity",               risk: "Med-High" },
    ],
  },
  {
    name: "🛡️ Defense & Drones",
    color: "595959",
    description: "Defense technology and drone companies — $1.5T defense budget tailwind",
    stocks: [
      { ticker: "ONDS",   company: "Ondas Holdings",               focus: "Drones and defense tech",                           risk: "Very High" },
      { ticker: "KTOS",   company: "Kratos Defense",               focus: "Unmanned systems, missile defense, space",          risk: "High"      },
      { ticker: "RCAT",   company: "Red Cat Holdings",             focus: "Military drone systems & edge AI",                  risk: "Very High" },
      { ticker: "ACHR",   company: "Archer Aviation",              focus: "eVTOL aircraft for defense & urban mobility",       risk: "Very High" },
      { ticker: "KRKNF",  company: "Kraken Robotics",              focus: "Underwater robotics, sonar & maritime defense",     risk: "Very High" },
      { ticker: "AXON",   company: "Axon Enterprise",              focus: "AI cameras, Tasers & law enforcement tech platform", risk: "Med-High" },
      { ticker: "JOBY",   company: "Joby Aviation",                focus: "eVTOL aircraft with USAF & commercial contracts",   risk: "Very High" },
      { ticker: "LDOS",   company: "Leidos Holdings",              focus: "Defense AI, IT systems & classified programs",      risk: "Medium"    },
      { ticker: "BAH",    company: "Booz Allen Hamilton",          focus: "Government AI consulting & analytics",              risk: "Medium"    },
      { ticker: "SAIC",   company: "Science Applications Intl",    focus: "Defense tech & government IT services",             risk: "Medium"    },
    ],
  },
  {
    name: "🚀 Space Economy",
    color: "002060",
    description: "Space infrastructure — long-duration compounder with SpaceX IPO catalyst",
    stocks: [
      { ticker: "RKLB",  company: "Rocket Lab USA",         focus: "Space economy & launch infrastructure",                  risk: "High"      },
      { ticker: "ASTS",  company: "AST SpaceMobile",        focus: "Space-based cellular broadband network",                 risk: "Very High" },
      { ticker: "LUNR",  company: "Intuitive Machines",     focus: "Lunar landers, NASA contracts, space services",          risk: "High"      },
      { ticker: "IRDM",  company: "Iridium Communications", focus: "Global satellite network & IoT connectivity",            risk: "Medium"    },
      { ticker: "VSAT",  company: "Viasat Inc",             focus: "Satellite broadband & government communications",        risk: "High"      },
      { ticker: "GSAT",  company: "Globalstar Inc",         focus: "LEO satellite network with Apple connectivity deal",     risk: "High"      },
      { ticker: "BKSY",  company: "BlackSky Technology",    focus: "Geospatial intelligence & real-time satellite imagery",  risk: "Very High" },
      { ticker: "RDW",   company: "Redwire Corp",           focus: "Space infrastructure components & NASA contracts",       risk: "Very High" },
      { ticker: "SPIR",  company: "Spire Global",           focus: "Weather, maritime & aviation data from satellites",      risk: "Very High" },
    ],
  },
  {
    name: "🧬 Biotech & Healthcare Innovation",
    color: "00B050",
    description: "High-growth biotech and healthcare tech plays with AI-driven drug discovery catalysts",
    stocks: [
      { ticker: "RXRX",  company: "Recursion Pharmaceuticals", focus: "AI-driven drug discovery platform",                   risk: "Very High" },
      { ticker: "SDGR",  company: "Schrödinger Inc",           focus: "Physics-based AI drug design software",               risk: "Very High" },
      { ticker: "ABCL",  company: "AbCellera Biologics",       focus: "AI antibody discovery platform",                      risk: "Very High" },
      { ticker: "TWST",  company: "Twist Bioscience",          focus: "Synthetic DNA & genomics tools",                      risk: "Very High" },
      { ticker: "PACB",  company: "Pacific Biosciences",       focus: "Long-read DNA sequencing instruments",                 risk: "Very High" },
      { ticker: "BEAM",  company: "Beam Therapeutics",         focus: "Base editing gene therapy platform",                  risk: "Very High" },
      { ticker: "VERV",  company: "Verve Therapeutics",        focus: "Cardiovascular gene editing therapy",                  risk: "Very High" },
      { ticker: "NTLA",  company: "Intellia Therapeutics",     focus: "CRISPR-based in vivo gene editing",                   risk: "Very High" },
      { ticker: "EDIT",  company: "Editas Medicine",           focus: "CRISPR gene editing therapies",                       risk: "Very High" },
      { ticker: "FATE",  company: "Fate Therapeutics",         focus: "iPSC-derived cell therapy platform",                  risk: "Very High" },
      { ticker: "HIMS",  company: "Hims & Hers Health",        focus: "Direct-to-consumer health & telehealth platform",     risk: "High"      },
      { ticker: "ACCD",  company: "Accolade Inc",              focus: "AI-powered health navigation & advocacy",             risk: "High"      },
    ],
  },
  {
    name: "🤖 Robotics & Automation",
    color: "FF0000",
    description: "Physical AI — the next wave of automation from warehouses to humanoid robots",
    stocks: [
      { ticker: "BDTX",  company: "Black Diamond Therapeutics", focus: "Precision oncology — AI-matched tumor mutations",    risk: "Very High" },
      { ticker: "FARO",  company: "FARO Technologies",          focus: "3D measurement & digital twin for robotics",         risk: "High"      },
      { ticker: "ISRG",  company: "Intuitive Surgical",         focus: "Robotic surgery systems — market leader",             risk: "Medium"    },
      { ticker: "GRAB",  company: "Grab Holdings",              focus: "SE Asia super-app: ride, food, fintech",              risk: "High"      },
      { ticker: "RBOT",  company: "Vicarious Surgical",         focus: "Humanoid surgical robot technology",                  risk: "Very High" },
      { ticker: "GFAI",  company: "Guardforce AI",              focus: "AI security robotics for commercial deployment",      risk: "Very High" },
      { ticker: "BFLY",  company: "Butterfly Network",          focus: "Handheld ultrasound with AI diagnostics",             risk: "High"      },
      { ticker: "TNDM",  company: "Tandem Diabetes Care",       focus: "AI-powered insulin delivery systems",                 risk: "High"      },
      { ticker: "AAON",  company: "AAON Inc",                   focus: "HVAC systems for data centers & commercial",          risk: "Medium"    },
    ],
  },
  {
    name: "💳 Fintech & Digital Finance",
    color: "FFD700",
    description: "Next-generation financial infrastructure — payments, crypto rails, and embedded finance",
    stocks: [
      { ticker: "AFRM",  company: "Affirm Holdings",        focus: "Buy-now-pay-later & AI underwriting platform",           risk: "High"      },
      { ticker: "SOFI",  company: "SoFi Technologies",      focus: "Digital bank: loans, brokerage, credit cards",           risk: "High"      },
      { ticker: "UPST",  company: "Upstart Holdings",       focus: "AI-powered consumer lending platform",                   risk: "Very High" },
      { ticker: "NU",    company: "Nu Holdings",            focus: "Latin America's leading digital bank (Brazil)",          risk: "High"      },
      { ticker: "HOOD",  company: "Robinhood Markets",      focus: "Retail brokerage + crypto & prediction markets",         risk: "High"      },
      { ticker: "MARA",  company: "MARA Holdings",          focus: "Bitcoin mining & digital asset infrastructure",          risk: "Very High" },
      { ticker: "RIOT",  company: "Riot Platforms",         focus: "Bitcoin mining infrastructure at scale",                 risk: "Very High" },
      { ticker: "CLSK",  company: "CleanSpark Inc",         focus: "Bitcoin mining with sustainable energy focus",           risk: "Very High" },
      { ticker: "COIN",  company: "Coinbase Global",        focus: "Largest US crypto exchange & custody platform",          risk: "High"      },
      { ticker: "PYPL",  company: "PayPal Holdings",        focus: "Digital payments & commerce platform",                   risk: "Medium"    },
      { ticker: "BILL",  company: "Bill.com Holdings",      focus: "AI-powered SMB financial operations platform",           risk: "High"      },
      { ticker: "RELY",  company: "Remitly Global",         focus: "Digital remittance & international money transfers",     risk: "High"      },
    ],
  },
  {
    name: "🛒 Consumer & Platform Tech",
    color: "9B59B6",
    description: "High-growth consumer platforms with durable network effects and AI monetization",
    stocks: [
      { ticker: "MELI",  company: "MercadoLibre Inc",       focus: "Latin America's dominant e-commerce & fintech platform", risk: "Med-High"  },
      { ticker: "SHOP",  company: "Shopify Inc",            focus: "Global commerce platform & merchant solutions",           risk: "Med-High"  },
      { ticker: "APP",   company: "Applovin Corp",          focus: "AI-driven mobile advertising & gaming platform",          risk: "High"      },
      { ticker: "RBLX",  company: "Roblox Corp",            focus: "Metaverse gaming platform — youth engagement",            risk: "High"      },
      { ticker: "DUOL",  company: "Duolingo Inc",           focus: "AI-powered language learning platform",                   risk: "Med-High"  },
      { ticker: "CAVA",  company: "CAVA Group Inc",         focus: "Mediterranean fast-casual restaurant chain",              risk: "High"      },
      { ticker: "CELH",  company: "Celsius Holdings",       focus: "Premium energy drink brand — strong retail growth",       risk: "High"      },
      { ticker: "DASH",  company: "DoorDash Inc",           focus: "Food delivery & local commerce marketplace",              risk: "Med-High"  },
    ],
  },
];

export const ALL_TICKERS: string[] = CATEGORIES.flatMap(c => c.stocks.map(s => s.ticker));

export const TICKER_TO_COMPANY: Record<string, string> = Object.fromEntries(
  CATEGORIES.flatMap(c => c.stocks.map(s => [s.ticker, s.company]))
);
